//include <../templates/basic-dims.scad>
//include <../templates/t_simple-segment.scad>
//include <../templates/t_simple-wall-corner.scad>
//include <../templates/t_simple-door.scad>
//include <../templates/t_flat-roof.scad>
//include <../templates/t_door-frame.scad>
include <../templates/t_shop-window.scad>
include <../templates/t_simple-window.scad>
include <../templates/t_window-frame.scad>